export const ActionTypes = {
  USER_LOAD_REQUEST: "USER_LOAD_REQUEST",
  USER_LOAD_SUCCESS: "USER_LOAD_SUCCESS",
  USER_LOAD_FAIL: "USER_LOAD_FAIL",

  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAIL: "USER_REGISTER_FAIL",

  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",

  USER_LOGOUT: "USER_LOGOUT",

  BOOK_LIST_REQUEST: "BOOK_LIST_REQUEST",
  BOOK_LIST_SUCCESS: "BOOK_LIST_SUCCESS",
  BOOK_LIST_FAIL: "BOOK_LIST_FAIL",

  USER_BOOK_LIST_REQUEST: "USER_BOOK_LIST_REQUEST",
  USER_BOOK_LIST_SUCCESS: "USER_BOOK_LIST_SUCCESS",
  USER_BOOK_LIST_FAIL: "USER_BOOK_LIST_FAIL",

  BOOK_DETAILS_REQUEST: "BOOK_DETAILS_REQUEST",
  BOOK_DETAILS_SUCCESS: "BOOK_DETAILS_SUCCESS",
  BOOK_DETAILS_FAIL: "BOOK_DETAILS_FAIL",

  BOOK_SAVE_REQUEST: "BOOK_SAVE_REQUEST",
  BOOK_SAVE_SUCCESS: "BOOK_SAVE_SUCCESS",
  BOOK_SAVE_FAIL: "BOOK_SAVE_FAIL",

  BOOK_DELETE_REQUEST: "BOOK_DELETE_REQUEST",
  BOOK_DELETE_SUCCESS: "BOOK_DELETE_SUCCESS",
  BOOK_DELETE_FAIL: "BOOK_DELETE_FAIL",

  BOOK_READ_REQUEST: "BOOK_READ_REQUEST",
  BOOK_READ_SUCCESS: "BOOK_READ_SUCCESS",
  BOOK_READ_FAIL: "BOOK_READ_FAIL",

  BOOK_RATING_REQUEST: "BOOK_RATING_REQUEST",
  BOOK_RATING_SUCCESS: "BOOK_RATING_SUCCESS",
  BOOK_RATING_FAIL: "BOOK_RATING_FAIL",
};
